apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-leader-pv
  labels:
    run: jenkins-leader
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-63287ac4
    fsType: ext4