FROM smesch/jenkins-kubernetes-leader:2.32.3
MAINTAINER Steven Eschinger <steven@eschinger.com>

COPY jobs /usr/share/jenkins/ref/jobs
COPY sns.xml /usr/share/jenkins/ref/org.jenkinsci.plugins.snsnotify.AmazonSNSNotifier.xml
